### ISSUE TITLE
Move all exception classes to a shared location and consolidate

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdaq#125]
## Current Behavior

[pcdsdaq/exceptions.py
](https://github.com/pcdshub/pcdsdaq/blob/cc9818ad3d3c0310e02e8925c4c611543fbca48d/pcdsdaq/exceptions.py#L1)[pcdsdaq/daq/interface.py](https://github.com/pcdshub/pcdsdaq/blob/cc9818ad3d3c0310e02e8925c4c611543fbca48d/pcdsdaq/daq/interface.py#L93)

**Comment by klauer** [comment]
Oops, I missed those exceptions defined there. 

I'll make a quick follow-up PR unless you're planning to wrap it into your upcoming PR
