### ISSUE TITLE
Keep DAQ running after plan

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdaq#29]
Often times, operators want to run their scan (with record=True), then restart the DAQ in non-record mode at the end so they can still view detectors and cameras. Might be nice to support this mode of operation by having a `daq_cleanup` plan that restarts the DAQ in the different mode if desired by the operator.

**Comment by ZLLentz** [comment]
Seems reasonable, making the distinction between modes of operation "record and not record" vs "run and not run". My only concern is that the python session keeps control of the DAQ so it may be frustrating to not be able to stop the daq from the GUI to change config, partition, evr, etc.

**Comment by ZLLentz** [comment]
@teddyrendahl one more idea: is it desirable to have a mode that disconnects the daq after a run? So then you have three configurable behaviors:

1. After a run, stay connected but do not run the DAQ (current behavior)
2. After a run, restart with `record=False`, running forever until you disconnect or start a new run (this enhancement)
3. After a run, disconnect and cede control to the GUI (my suggestion)

**Comment by teddyrendahl** [comment]
What about not having modes and just returning to the state you had before the scan? But yes I like being able to do all three.

**Comment by ZLLentz** [comment]
Yes, I think you are correct. Simply return to the state we had before the scan. If you want to avoid a disconnect like in your example you connect prior to running the plan.

So I just cache `self.state` and act accordingly:

- "Disconnected": disconnect after plan
- "Connected", "Configured", or "Open": end the run and do nothing else
- "Running": start a new run with `record=False`
