### ISSUE TITLE
Rapid DAQ Run Transitions

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdaq#40]
When rapidly cycling the DAQ there appears to be an issue with the status object that is created. An example can be seen in:

`cxipython/logs/2018_09/cxiopr_24_17h05m22s.log` @ line 4050 or so

**Comment by ZLLentz** [comment]
Current plan is to recreate this with the sim pydaq and see what raw commands we're asking and with what timing, then create a really basic script with only raw pydaq commands and diagnose what causes the issue

**Comment by ZLLentz** [comment]
It would need to be on `stop` because this happens during a run, but I think the idea is sound. I want to understand fully what's going on first though.

**Comment by ZLLentz** [comment]
Probably opt for something less crude, like checking for the time since last `stop` and sleeping for the difference between that and the settle time.

**Comment by ZLLentz** [comment]
There seem to be two issues: a rare `ValueError` that can happen immediately and kill the scan on `pydaq.Control.begin`, followed-up by a nonsensical message about too much time elapsing, and then a second deterministic issue that seems to occur when I set the sleep time to 0.25, always stalling out with a full timeout on the third step of the scan.
