### ISSUE TITLE
pcdsdaq_lib_setup breaks flake8

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdaq#61]
## Expected Behavior

flake8 works normally after setting up the daq libs

## Current Behavior

a flake8 failure forces a logout/exit from the current bash shell

pointed out to me by @ZryletTC

**Comment by klauer** [comment]
❗️

**Comment by ZryletTC** [comment]
This is not limited to flake8 and seems to happen anytime something has a non-zero exit status.
I've seen it happen with run_tests.py in pcdsdevices and even when bash reports 'command not found'

**Comment by klauer** [comment]
Oh, this is then `set -e` in bash. If you do a `set +e` prior to running flake8, it won't exit.

**Comment by ZryletTC** [comment]
Makes sense, is there a reason pcdsdaq_lib_setup doesn't have a `set +e`?

**Comment by klauer** [comment]
For a script you're intended to source, it's pretty bad to have `set -e`. We should remove this line:
https://github.com/pcdshub/pcdsdaq/blob/d314ed4a2c578ea2e620afe023f787d5321e8bdf/bin/pcdsdaq_lib_setup#L6

**Comment by ZLLentz** [comment]
My bad on this one
