### ISSUE TITLE
Daq class interprets negative events as finite-length scans

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdaq#82]
## Expected Behavior

events=-1 should work as an infinite length scan and be identified as such in all cases
OR
events=-1 should be a rejected input

## Current Behavior

events=-1 does work as an infinite length scan, but is identified as finite-length because `bool(-1)` is `True`

**Comment by ZryletTC** [comment]
I vote for option events=-1 works as infinite length

**Comment by klauer** [comment]
So: 
* Overall check `assert events >= -1, 'Invalid event count'`
* `is_infinite_length_scan = events in (-1, 0)`

**Comment by ZLLentz** [comment]
:+1: I may work on this today, but it would wait till the PAMM to do a full test.
