### ISSUE TITLE
Noarch conda build

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdaq#95]
## Expected Behavior

It'd be nice to have a noarch conda build

## Current Behavior

We only have linux-64 builds for now

## Context

When testing stuff out on a mac, anything that depends on this package doesn't work through conda. I can still install through pip but it'd be nice to not have to.

**Comment by ZLLentz** [comment]
The recipe needs some additional work, simply marking as noarch will cause the build to fail. See #97.

**Comment by ZLLentz** [comment]
oops my b

**Comment by ZryletTC** [comment]
No problem, just noticed you probably didn't mean to do that.
Good to know Github'll close issues even if the "closes" is struckthrough
